### ISSUE TITLE
Ask for help: about code

### ISSUE THREAD

**Issue by WANGrfy** [UCLA-StarAI/NaCL#4] opened 2020-06-03 05:20 UTC
Hello, I am a graduate student of Northeast University of China. I have read the article "what to expect of classifiers? Reasoning about logistic regression with missing features" in recent days. I think the author's ideas and thoughts are very good. Later, I downloaded your code about this article on GitHub, and encountered some problems. I installed the required Python library. However, when running the program about MINST dataset, when the program runs to use "gpkit" to solve, there will be insufficient memory. My computer is 12gb of running memory. My initial idea is to reduce the dimension of data set, change the number of training samples from 60000 to 60, and the number of test sets from 10000 to 10. Use a small data set, but I find that the memory is still completely occupied. The program didn't finish running for eight hours. So I want to ask you, can your program run successfully? What system is your computer and how much memory? And if the number of samples is reduced, can it also operate normally? Will there be a memory overflow?
I'm sorry to disturb you. I hope you can answer for me. Thank you very much.

**Comment by khosravipasha** [comment] 2020-06-03 06:07
Hi @WANGrfy thanks for the question. I will double check and try to run my end again to see how much RAM you would need. I think 12GB should be more than enough.

### Few quick questions for me to try reproduce the error:

1. What is your python version and what is the gpkit version? 

2. And which ones of gpkit's backend solvers are you using? We suggest using mosek as others are much slower. See more info [here](https://gpkit.readthedocs.io/en/latest/installation.html#installing-mosek).

3. Have you tried the other datasets? For example can you successfuly run [this notebook](https://github.com/UCLA-StarAI/NaCL/blob/master/notebooks/missing_adult.ipynb). How long does it take to solve in the NaCL step? For ours it took few seconds. 

4. Are you running [this script](https://github.com/UCLA-StarAI/NaCL/blob/master/code/train_for_mnistk.py) for traininig NaCL on mnist?  

### Some notes about runtime:
Number of training samples don't actually change the runtime much, we only read through the dataset once, the main bottleneck is gpkit solving the geometric programming, which from my experiments grows O(n^2) in time as you increase the features, so you can get a good estimate of how long it should take by let's say keeping 50 pixels of mnist and see how long it takes and then multiplying that by 256. That being said 8 hours seems too long and it took only 20-30 min for us. I don't have a good estimate of how much memory usage it needs, will run things on my end and get back to you.

**Comment by WANGrfy** [comment] 2020-06-07 17:07
Thank you very much for your reply. You are so kind. It helps me a lot. Now the problem of memory overflow is solved.
Let me first answer your questions:
1. My python = = 2.7, gpkit = = 0.7.0.0, numpy = = 1.14.2, tensorflow = = 1.15.0, tensorbboard = = 1.15.0, tensorflow estimator = = 1.15.1. Here's a question. You're requirements.txt The gpkit version is not mentioned in, so what version do you use?
2. I ran train directly_ for_ mnistk.py This file, so gpkit's back-end solver should be the default MOSEK, right?
3. I ran other data sets with errors. I was running missing_ adult.ipynb And it didn't work
4. I run this script on MNIST to train NaCl
After that, I have a question: I used Ubuntu system. The Ubuntu system version is 16.04lts. I downloaded anaconda. When I installed the tensorflow library, I prompted that there is no tensorflow = 1.15.2. The tensorflow version includes these:
 Collecting&nbsp;tensorflow==1.15.2
&nbsp;&nbsp;ERROR:&nbsp;Could&nbsp;not&nbsp;find&nbsp;a&nbsp;version&nbsp;that&nbsp;satisfies&nbsp;the&nbsp;requirement&nbsp;tensorflow==1.15.2&nbsp;(from&nbsp;versions:&nbsp;0.12.0rc0,&nbsp;0.12.0rc1,&nbsp;0.12.0,&nbsp;0.12.1,&nbsp;1.0.0,&nbsp;1.0.1,&nbsp;1.1.0rc0,&nbsp;1.1.0rc1,&nbsp;1.1.0rc2,&nbsp;1.1.0,&nbsp;1.2.0rc0,&nbsp;1.2.0rc1,&nbsp;1.2.0rc2,&nbsp;1.2.0,&nbsp;1.2.1,&nbsp;1.3.0rc0,&nbsp;1.3.0rc1,&nbsp;1.3.0rc2,&nbsp;1.3.0,&nbsp;1.4.0rc0,&nbsp;1.4.0rc1,&nbsp;1.4.0,&nbsp;1.4.1,&nbsp;1.5.0rc0,&nbsp;1.5.0rc1,&nbsp;1.5.0,&nbsp;1.5.1,&nbsp;1.6.0rc0,&nbsp;1.6.0rc1,&nbsp;1.6.0,&nbsp;1.7.0rc0,&nbsp;1.7.0rc1,&nbsp;1.7.0,&nbsp;1.7.1,&nbsp;1.8.0rc0,&nbsp;1.8.0rc1,&nbsp;1.8.0,&nbsp;1.9.0rc0,&nbsp;1.9.0rc1,&nbsp;1.9.0rc2,&nbsp;1.9.0,&nbsp;1.10.0rc0,&nbsp;1.10.0rc1,&nbsp;1.10.0,&nbsp;1.10.1,&nbsp;1.11.0rc0,&nbsp;1.11.0rc1,&nbsp;1.11.0rc2,&nbsp;1.11.0,&nbsp;1.12.0rc0,&nbsp;1.12.0rc1,&nbsp;1.12.0rc2,&nbsp;1.12.0,&nbsp;1.12.2,&nbsp;1.12.3,&nbsp;1.13.0rc0,&nbsp;1.13.0rc1,&nbsp;1.13.0rc2,&nbsp;1.13.1,&nbsp;1.13.2,&nbsp;1.14.0rc0,&nbsp;1.14.0rc1,&nbsp;1.14.0,&nbsp;1.15.0rc0,&nbsp;1.15.0rc1,&nbsp;1.15.0rc2,&nbsp;1.15.0rc3,&nbsp;1.15.0,&nbsp;2.0.0a0,&nbsp;2.0.0b0,&nbsp;2.0.0b1,&nbsp;2.0.0rc0,&nbsp;2.0.0rc1,&nbsp;2.0.0rc2,&nbsp;2.0.0,&nbsp;2.1.0rc0,&nbsp;2.1.0rc1,&nbsp;2.1.0rc2,&nbsp;2.1.0)
ERROR:&nbsp;No&nbsp;matching&nbsp;distribution&nbsp;found&nbsp;for&nbsp;tensorflow==1.15.2 


So I downloaded tensorflow = 1.15.0, but for tensorflow 1.15.0, numpy's version is less than 2.0 and more than 1.6, so I want to ask you that the version of tensorflow you provided is no problem, right?
I miss_ adult.ipynb The test file has been sent to you through the email. You can see the error when I run it directly when you open it. There is an error in the learning NaCl, but I didn't continue to run it later.
Finally, thank you again for your warm help and hope to receive your reply.

**Comment by WANGrfy** [comment] 2020-06-07 17:11
https://github.com/WANGrfy/JuMP/blob/master/missing_adult.ipynb

**Comment by khosravipasha** [comment] 2020-06-08 02:15
Hi,

We don't actually use tensorflow other than for downloading the mnist dataset in this line (https://github.com/UCLA-StarAI/NaCL/blob/master/code/train_for_mnistk.py#L17), so any version that has that api should work, or you can actually remove tensor flow and instead load the mnist from somewhere else.

I don't recall which Gpkit version we used but latest version should be fine I think. One difference is that when this code was written gpkit did to not support python3, now they are moving to python3 since python2 is being depracated. But from the error you sent me I dont think that's the issue.

The error `OSError: [Errno 2] No such file or directory` means that `mosek_cli` is not setup correctly, I have had similar issues. There is another way of using mosek in gpkit by setting the `solver='mosek'`, instead of `solver='mosek_cli'`.  I suggest making sure gpkit can run mosek by using a small example to see if the problem is from mosek.  
Also this might help https://github.com/convexengineering/gpkit/issues/1297.

**Comment by khosravipasha** [comment] 2020-10-26 01:34
@WANGrfy 
I just recently ported the code to python3 and new gpkit, mosek. it does not depend on the old tensorflow anymore.
Also gpkit seems to be easier to setup with mosek with the new version, you can try try using the python3-refactor branch.

https://github.com/UCLA-StarAI/NaCL/tree/python3-refactor

**Closed as completed by khosravipasha** 2020-10-26 01:34 UTC
Labels: question

**Comment by WANGrfy** [comment] 2020-10-26 01:53
Thank you very much for telling me this, you are really nice. I will try again and study it carefully. I hope it can help me. I admire you, and I will learn from you. Thank you again.
